name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Point Docker to Minikube daemon
        run: minikube docker-env | Invoke-Expression

      - name: Build Docker image
        run: docker build --no-cache -t pregnancy-checker:latest ${{ github.workspace }}

      - name: Apply Kubernetes manifests
        run: kubectl apply -f k8s/

      - name: Rollout restart
        run: kubectl rollout restart deployment/pregnancy-checker

      - name: Wait for rollout
        run: kubectl rollout status deployment/pregnancy-checker --timeout=120s
